name: simple_validator
description: Simple Validator is a text validation library for Dart/Flutter developed in Dart
version: 0.0.1
homepage: https://github.com/murilosandiego/simple-validator

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  test: ^1.15.7
  test_coverage:
